### ISSUE TITLE
Set up master branch tracking on Github

### ISSUE THREAD

**Issue by n-fisher** [n-fisher/ModRank#14]
## Do This

- [x] Implement server rebuild/redeploy script
- [x] Set up server to listen for webhook and call script
- [x] Keepalive server using Docker or system hooks
- [x] Add webhook to Github
